### ISSUE TITLE
Add invisitekmaterials property

### ISSUE THREAD

**Issue by ghostrider-05** [RocketLeagueMapmaking/RL-Dummy-Classes#10]
Add the following property property to `MeshComponent`:
```uc
var(Rendering) const array<MaterialInterface> InvisiTekMaterials;
```

And in primitive component:
```diff
- var bool bUseAsOccluder;
+ var(Rendering) bool bUseAsOccluder;
```

**Comment by spencerarrasmith** [comment]
Added as part of this PR: https://github.com/RocketLeagueMapmaking/RL-Dummy-Classes/commit/8b104a15d386a2e10497044196797bf05351f669

**Comment by ghostrider-05** [comment]
Did you manage to recompile the new classes?

**Comment by spencerarrasmith** [comment]
They compile fine, but I didn't know how to test this
